export const publicPnr = (pnr: any, job: any) => ({
  airline: pnr.airline,
  clientName: job?.clientName ?? "",
  createdAt: new Date(pnr.createdAt).toISOString(),
  fareType: pnr.fareType ?? "",
  flightGroupId: pnr.flightGroupId ?? null,
  id: pnr._id,
  issuedSeats: pnr.issuedSeats,
  jobCardId: pnr.jobCardId,
  jobCode: job?.jobCode ?? "",
  pnrCode: pnr.pnrCode,
  route: pnr.route,
  status: pnr.status ?? "",
  totalSeats: pnr.totalSeats,
  updatedAt: new Date(pnr.updatedAt).toISOString(),
});

export const publicTicket = (
  ticket: any,
  traveller: any,
  pnr: any,
  job: any,
  travelBatch: any = null
) => ({
  cabinClass: ticket.cabinClass ?? "",
  clientName: job?.clientName ?? "",
  createdAt: new Date(ticket.createdAt).toISOString(),
  id: ticket._id,
  jobCardId: ticket.jobCardId,
  jobCode: job?.jobCode ?? "",
  mealPreference: ticket.mealPreference ?? "",
  paymentType: ticket.paymentType,
  pnrCode: pnr?.pnrCode ?? "",
  pnrId: ticket.pnrId ?? null,
  seatNumber: ticket.seatNumber ?? "",
  seatPreference: ticket.seatPreference ?? "",
  ticketNumber: ticket.ticketNumber ?? "",
  ticketStatus: ticket.ticketStatus,
  ticketType: ticket.ticketType ?? "",
  travelBatchCode: travelBatch?.batchCode ?? "",
  travelBatchId: traveller?.travelBatchId ?? "",
  travelBatchReference: travelBatch?.batchReference ?? "",
  travellerId: ticket.travellerId ?? null,
  travellerName: traveller?.fullName ?? "",
  updatedAt: new Date(ticket.updatedAt).toISOString(),
});
