/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as _exportSurface from "../_exportSurface.js";
import type * as _runtimeModules from "../_runtimeModules.js";
import type * as aiRuntime from "../aiRuntime.js";
import type * as auth from "../auth.js";
import type * as authAccountLinking from "../authAccountLinking.js";
import type * as authEmailDeliveries from "../authEmailDeliveries.js";
import type * as authEmailDeliveryIntents from "../authEmailDeliveryIntents.js";
import type * as authIdentityMigration from "../authIdentityMigration.js";
import type * as authSync from "../authSync.js";
import type * as bookings from "../bookings.js";
import type * as crm_activity from "../crm/activity.js";
import type * as crm_approvals from "../crm/approvals.js";
import type * as crm_closedLeadStageMigration from "../crm/closedLeadStageMigration.js";
import type * as crm_commandReceipts from "../crm/commandReceipts.js";
import type * as crm_commercialFileActions from "../crm/commercialFileActions.js";
import type * as crm_commercialFilePolicy from "../crm/commercialFilePolicy.js";
import type * as crm_commercialFilePurge from "../crm/commercialFilePurge.js";
import type * as crm_commercialFiles from "../crm/commercialFiles.js";
import type * as crm_commercialRecordChain from "../crm/commercialRecordChain.js";
import type * as crm_commercialRecordChainReads from "../crm/commercialRecordChainReads.js";
import type * as crm_confirmedOffer from "../crm/confirmedOffer.js";
import type * as crm_contractingPipelineCommands from "../crm/contractingPipelineCommands.js";
import type * as crm_contractingPipelinePolicy from "../crm/contractingPipelinePolicy.js";
import type * as crm_customerAttributionMigration from "../crm/customerAttributionMigration.js";
import type * as crm_dashboard from "../crm/dashboard.js";
import type * as crm_documentPreview from "../crm/documentPreview.js";
import type * as crm_documentPreviewActions from "../crm/documentPreviewActions.js";
import type * as crm_documentPreviewArtifact from "../crm/documentPreviewArtifact.js";
import type * as crm_documentPreviewAudit from "../crm/documentPreviewAudit.js";
import type * as crm_documentPreviewContract from "../crm/documentPreviewContract.js";
import type * as crm_documentPreviewHttp from "../crm/documentPreviewHttp.js";
import type * as crm_documentPreviewLifecycle from "../crm/documentPreviewLifecycle.js";
import type * as crm_documentPreviewRollout from "../crm/documentPreviewRollout.js";
import type * as crm_documentPreviewSource from "../crm/documentPreviewSource.js";
import type * as crm_documentPreviewToken from "../crm/documentPreviewToken.js";
import type * as crm_e2eAssertions from "../crm/e2eAssertions.js";
import type * as crm_e2eFixtures from "../crm/e2eFixtures.js";
import type * as crm_e2eRunOwnership from "../crm/e2eRunOwnership.js";
import type * as crm_e2eSeed from "../crm/e2eSeed.js";
import type * as crm_e2eSeedActions from "../crm/e2eSeedActions.js";
import type * as crm_e2eStaffProfiles from "../crm/e2eStaffProfiles.js";
import type * as crm_expenseApprovalWorkflow from "../crm/expenseApprovalWorkflow.js";
import type * as crm_expenseAttachmentActions from "../crm/expenseAttachmentActions.js";
import type * as crm_expenseAttachments from "../crm/expenseAttachments.js";
import type * as crm_expenseCommands from "../crm/expenseCommands.js";
import type * as crm_expenseLifecycle from "../crm/expenseLifecycle.js";
import type * as crm_expenseLifecycleMigration from "../crm/expenseLifecycleMigration.js";
import type * as crm_expenseMaterialIntegrity from "../crm/expenseMaterialIntegrity.js";
import type * as crm_expensePolicy from "../crm/expensePolicy.js";
import type * as crm_expenseReads from "../crm/expenseReads.js";
import type * as crm_expenseScope from "../crm/expenseScope.js";
import type * as crm_fileReturnContracts from "../crm/fileReturnContracts.js";
import type * as crm_fileValidation from "../crm/fileValidation.js";
import type * as crm_finance from "../crm/finance.js";
import type * as crm_financeMetricSync from "../crm/financeMetricSync.js";
import type * as crm_financeOverviewReads from "../crm/financeOverviewReads.js";
import type * as crm_financeTicketingReturnContracts from "../crm/financeTicketingReturnContracts.js";
import type * as crm_financeValidators from "../crm/financeValidators.js";
import type * as crm_flightImports from "../crm/flightImports.js";
import type * as crm_importActions from "../crm/importActions.js";
import type * as crm_importBatchPolicy from "../crm/importBatchPolicy.js";
import type * as crm_importProcessor from "../crm/importProcessor.js";
import type * as crm_importReturnContracts from "../crm/importReturnContracts.js";
import type * as crm_importRowValidators from "../crm/importRowValidators.js";
import type * as crm_importRows from "../crm/importRows.js";
import type * as crm_importWorkerPolicy from "../crm/importWorkerPolicy.js";
import type * as crm_imports from "../crm/imports.js";
import type * as crm_inboundQueryIntents from "../crm/inboundQueryIntents.js";
import type * as crm_invoiceCommands from "../crm/invoiceCommands.js";
import type * as crm_invoiceOutstandingPolicy from "../crm/invoiceOutstandingPolicy.js";
import type * as crm_invoiceOutstandingProjection from "../crm/invoiceOutstandingProjection.js";
import type * as crm_invoiceReads from "../crm/invoiceReads.js";
import type * as crm_jobCardChecklist from "../crm/jobCardChecklist.js";
import type * as crm_jobCardChecklistCommands from "../crm/jobCardChecklistCommands.js";
import type * as crm_jobCardCommandCenter from "../crm/jobCardCommandCenter.js";
import type * as crm_jobCardCommands from "../crm/jobCardCommands.js";
import type * as crm_jobCardConstants from "../crm/jobCardConstants.js";
import type * as crm_jobCardCreation from "../crm/jobCardCreation.js";
import type * as crm_jobCardDeletion from "../crm/jobCardDeletion.js";
import type * as crm_jobCardNotifications from "../crm/jobCardNotifications.js";
import type * as crm_jobCardReads from "../crm/jobCardReads.js";
import type * as crm_jobCardRelations from "../crm/jobCardRelations.js";
import type * as crm_jobCardTravelBatchCommands from "../crm/jobCardTravelBatchCommands.js";
import type * as crm_jobCardVisibility from "../crm/jobCardVisibility.js";
import type * as crm_jobCards from "../crm/jobCards.js";
import type * as crm_leave from "../crm/leave.js";
import type * as crm_leaveApprovers from "../crm/leaveApprovers.js";
import type * as crm_leaveLapse from "../crm/leaveLapse.js";
import type * as crm_leaveMatrixData from "../crm/leaveMatrixData.js";
import type * as crm_leavePolicy from "../crm/leavePolicy.js";
import type * as crm_lib from "../crm/lib.js";
import type * as crm_lib_activity from "../crm/lib/activity.js";
import type * as crm_lib_bulkOps from "../crm/lib/bulkOps.js";
import type * as crm_lib_codes from "../crm/lib/codes.js";
import type * as crm_lib_documentPreviewImageSafety from "../crm/lib/documentPreviewImageSafety.js";
import type * as crm_lib_e2eAuth from "../crm/lib/e2eAuth.js";
import type * as crm_lib_e2eOwnership from "../crm/lib/e2eOwnership.js";
import type * as crm_lib_inboundIntentPreparation from "../crm/lib/inboundIntentPreparation.js";
import type * as crm_lib_leavePolicy from "../crm/lib/leavePolicy.js";
import type * as crm_lib_majorCapabilityPreparation from "../crm/lib/majorCapabilityPreparation.js";
import type * as crm_lib_notifications from "../crm/lib/notifications.js";
import type * as crm_lib_operationalAdminAccess from "../crm/lib/operationalAdminAccess.js";
import type * as crm_lib_operationalControls from "../crm/lib/operationalControls.js";
import type * as crm_lib_operationalTargetIdentity from "../crm/lib/operationalTargetIdentity.js";
import type * as crm_lib_portalFileDownloadLimit from "../crm/lib/portalFileDownloadLimit.js";
import type * as crm_lib_portalFileDownloadPolicy from "../crm/lib/portalFileDownloadPolicy.js";
import type * as crm_lib_presentation from "../crm/lib/presentation.js";
import type * as crm_lib_productionTestExecution from "../crm/lib/productionTestExecution.js";
import type * as crm_lib_productionTestRecipes from "../crm/lib/productionTestRecipes.js";
import type * as crm_lib_recordScope from "../crm/lib/recordScope.js";
import type * as crm_lib_rolePolicy from "../crm/lib/rolePolicy.js";
import type * as crm_lib_staffAccess from "../crm/lib/staffAccess.js";
import type * as crm_lib_validators from "../crm/lib/validators.js";
import type * as crm_listSearch from "../crm/listSearch.js";
import type * as crm_metricAggregates from "../crm/metricAggregates.js";
import type * as crm_metricDirty from "../crm/metricDirty.js";
import type * as crm_metricProjection from "../crm/metricProjection.js";
import type * as crm_metricTypes from "../crm/metricTypes.js";
import type * as crm_miscReturnContracts from "../crm/miscReturnContracts.js";
import type * as crm_navShortcuts from "../crm/navShortcuts.js";
import type * as crm_notificationCleanup from "../crm/notificationCleanup.js";
import type * as crm_notificationEmailConfig from "../crm/notificationEmailConfig.js";
import type * as crm_notificationEmailDelivery from "../crm/notificationEmailDelivery.js";
import type * as crm_notificationEmailDetails from "../crm/notificationEmailDetails.js";
import type * as crm_notificationEmailLedger from "../crm/notificationEmailLedger.js";
import type * as crm_notificationEmails from "../crm/notificationEmails.js";
import type * as crm_notificationPaths from "../crm/notificationPaths.js";
import type * as crm_notificationReads from "../crm/notificationReads.js";
import type * as crm_notificationSummary from "../crm/notificationSummary.js";
import type * as crm_notificationUnreadProjection from "../crm/notificationUnreadProjection.js";
import type * as crm_notificationUnreadProjectionMigration from "../crm/notificationUnreadProjectionMigration.js";
import type * as crm_operationTimePolicy from "../crm/operationTimePolicy.js";
import type * as crm_operationalSnapshots from "../crm/operationalSnapshots.js";
import type * as crm_operationsReturnContracts from "../crm/operationsReturnContracts.js";
import type * as crm_ops from "../crm/ops.js";
import type * as crm_paginationPolicy from "../crm/paginationPolicy.js";
import type * as crm_passengerExportCleanup from "../crm/passengerExportCleanup.js";
import type * as crm_passengerExportFunctionReferences from "../crm/passengerExportFunctionReferences.js";
import type * as crm_passengerExportOperations from "../crm/passengerExportOperations.js";
import type * as crm_passengerExportPolicy from "../crm/passengerExportPolicy.js";
import type * as crm_passengerExportSource from "../crm/passengerExportSource.js";
import type * as crm_passengerExportSourceContract from "../crm/passengerExportSourceContract.js";
import type * as crm_passengerExportWorkbook from "../crm/passengerExportWorkbook.js";
import type * as crm_passengerExportWorker from "../crm/passengerExportWorker.js";
import type * as crm_passengerImportCommit from "../crm/passengerImportCommit.js";
import type * as crm_passengerImportOperations from "../crm/passengerImportOperations.js";
import type * as crm_passengerImportReceipts from "../crm/passengerImportReceipts.js";
import type * as crm_passengerImportRows from "../crm/passengerImportRows.js";
import type * as crm_passengerKindPolicy from "../crm/passengerKindPolicy.js";
import type * as crm_passport from "../crm/passport.js";
import type * as crm_passportActions from "../crm/passportActions.js";
import type * as crm_passportExpiry from "../crm/passportExpiry.js";
import type * as crm_passportUploadTickets from "../crm/passportUploadTickets.js";
import type * as crm_passportUploadValidation from "../crm/passportUploadValidation.js";
import type * as crm_peopleWorkflowReturnContracts from "../crm/peopleWorkflowReturnContracts.js";
import type * as crm_pnrCleanup from "../crm/pnrCleanup.js";
import type * as crm_pnrCommands from "../crm/pnrCommands.js";
import type * as crm_pnrReads from "../crm/pnrReads.js";
import type * as crm_productionTestLab from "../crm/productionTestLab.js";
import type * as crm_proposalAttachmentActions from "../crm/proposalAttachmentActions.js";
import type * as crm_proposalAttachmentSummary from "../crm/proposalAttachmentSummary.js";
import type * as crm_proposalAttachments from "../crm/proposalAttachments.js";
import type * as crm_proposalDocument from "../crm/proposalDocument.js";
import type * as crm_proposalDocumentState from "../crm/proposalDocumentState.js";
import type * as crm_proposalHandoffCommands from "../crm/proposalHandoffCommands.js";
import type * as crm_proposalLinkProjection from "../crm/proposalLinkProjection.js";
import type * as crm_proposalReads from "../crm/proposalReads.js";
import type * as crm_proposalRelationSummary from "../crm/proposalRelationSummary.js";
import type * as crm_proposalRelations from "../crm/proposalRelations.js";
import type * as crm_proposalReturnContracts from "../crm/proposalReturnContracts.js";
import type * as crm_proposalVisibility from "../crm/proposalVisibility.js";
import type * as crm_proposalWriteCommands from "../crm/proposalWriteCommands.js";
import type * as crm_proposals from "../crm/proposals.js";
import type * as crm_queries from "../crm/queries.js";
import type * as crm_queryAttachmentActions from "../crm/queryAttachmentActions.js";
import type * as crm_queryAttachments from "../crm/queryAttachments.js";
import type * as crm_queryCommands from "../crm/queryCommands.js";
import type * as crm_queryCommercialProjection from "../crm/queryCommercialProjection.js";
import type * as crm_queryCreation from "../crm/queryCreation.js";
import type * as crm_queryDeletion from "../crm/queryDeletion.js";
import type * as crm_queryNotifications from "../crm/queryNotifications.js";
import type * as crm_queryReads from "../crm/queryReads.js";
import type * as crm_queryStatusPolicy from "../crm/queryStatusPolicy.js";
import type * as crm_queryTeamAssignment from "../crm/queryTeamAssignment.js";
import type * as crm_queryValidators from "../crm/queryValidators.js";
import type * as crm_rateLimitMaintenance from "../crm/rateLimitMaintenance.js";
import type * as crm_referenceTimePolicy from "../crm/referenceTimePolicy.js";
import type * as crm_recoveryCenter from "../crm/recoveryCenter.js";
import type * as crm_reports from "../crm/reports.js";
import type * as crm_returnContracts from "../crm/returnContracts.js";
import type * as crm_salesPipelineCommands from "../crm/salesPipelineCommands.js";
import type * as crm_salesPipelinePolicy from "../crm/salesPipelinePolicy.js";
import type * as crm_savedViews from "../crm/savedViews.js";
import type * as crm_seatCommands from "../crm/seatCommands.js";
import type * as crm_seatReads from "../crm/seatReads.js";
import type * as crm_settings from "../crm/settings.js";
import type * as crm_staff from "../crm/staff.js";
import type * as crm_staffAction from "../crm/staffAction.js";
import type * as crm_staffImport from "../crm/staffImport.js";
import type * as crm_staffSettingsReturnContracts from "../crm/staffSettingsReturnContracts.js";
import type * as crm_staffWorkbookUpdates from "../crm/staffWorkbookUpdates.js";
import type * as crm_storageReferences from "../crm/storageReferences.js";
import type * as crm_ticketCommands from "../crm/ticketCommands.js";
import type * as crm_ticketReads from "../crm/ticketReads.js";
import type * as crm_ticketStatusPolicy from "../crm/ticketStatusPolicy.js";
import type * as crm_ticketing from "../crm/ticketing.js";
import type * as crm_ticketingAssignmentPolicy from "../crm/ticketingAssignmentPolicy.js";
import type * as crm_ticketingDashboardReads from "../crm/ticketingDashboardReads.js";
import type * as crm_ticketingIntakePolicy from "../crm/ticketingIntakePolicy.js";
import type * as crm_ticketingPresentation from "../crm/ticketingPresentation.js";
import type * as crm_ticketingValidators from "../crm/ticketingValidators.js";
import type * as crm_travelBatchPolicy from "../crm/travelBatchPolicy.js";
import type * as crm_travellers from "../crm/travellers.js";
import type * as crm_validateReturnContract from "../crm/validateReturnContract.js";
import type * as crm_visa from "../crm/visa.js";
import type * as crm_workflowNudgeRun from "../crm/workflowNudgeRun.js";
import type * as crm_workflowNudges from "../crm/workflowNudges.js";
import type * as crons from "../crons.js";
import type * as customerConfirmedTrips from "../customerConfirmedTrips.js";
import type * as customerJourneyModel from "../customerJourneyModel.js";
import type * as e2eDeploymentIdentity from "../e2eDeploymentIdentity.js";
import type * as http from "../http.js";
import type * as lib_aiRateLimit from "../lib/aiRateLimit.js";
import type * as lib_authEmailDelivery from "../lib/authEmailDelivery.js";
import type * as lib_authEmailHtml from "../lib/authEmailHtml.js";
import type * as lib_authIdentity from "../lib/authIdentity.js";
import type * as lib_authIdentityMigration from "../lib/authIdentityMigration.js";
import type * as lib_authOriginPolicy from "../lib/authOriginPolicy.js";
import type * as lib_authSync from "../lib/authSync.js";
import type * as lib_betterAuthEmail from "../lib/betterAuthEmail.js";
import type * as lib_betterAuthLookup from "../lib/betterAuthLookup.js";
import type * as lib_bootstrapAuthority from "../lib/bootstrapAuthority.js";
import type * as lib_customerIdentityAccess from "../lib/customerIdentityAccess.js";
import type * as lib_emailConfig from "../lib/emailConfig.js";
import type * as lib_encryption from "../lib/encryption.js";
import type * as lib_formatDate from "../lib/formatDate.js";
import type * as lib_importContractValidators from "../lib/importContractValidators.js";
import type * as lib_passportPayloadCrypto from "../lib/passportPayloadCrypto.js";
import type * as lib_paymentMutationAuth from "../lib/paymentMutationAuth.js";
import type * as lib_profileFallback from "../lib/profileFallback.js";
import type * as lib_rateLimiterComponent from "../lib/rateLimiterComponent.js";
import type * as lib_roomTypeValidators from "../lib/roomTypeValidators.js";
import type * as lib_roomTypes from "../lib/roomTypes.js";
import type * as lib_runtimeValues from "../lib/runtimeValues.js";
import type * as lib_sacredBharatAliases from "../lib/sacredBharatAliases.js";
import type * as lib_sacredBharatGroups from "../lib/sacredBharatGroups.js";
import type * as lib_sacredBharatGuestMerge from "../lib/sacredBharatGuestMerge.js";
import type * as lib_sacredBharatInvites from "../lib/sacredBharatInvites.js";
import type * as lib_sacredBharatLeaderboard from "../lib/sacredBharatLeaderboard.js";
import type * as lib_sacredBharatLeaderboardRank from "../lib/sacredBharatLeaderboardRank.js";
import type * as lib_sacredBharatScoring from "../lib/sacredBharatScoring.js";
import type * as lib_staffAuthRepair from "../lib/staffAuthRepair.js";
import type * as lib_travelBatchSummary from "../lib/travelBatchSummary.js";
import type * as migrationAuth from "../migrationAuth.js";
import type * as migrations from "../migrations.js";
import type * as operationalScheduledJobs from "../operationalScheduledJobs.js";
import type * as publicReturnContracts from "../publicReturnContracts.js";
import type * as sacredBharat from "../sacredBharat.js";
import type * as sacredBharatEditionEvents from "../sacredBharatEditionEvents.js";
import type * as sacredBharatGroupMembershipMigration from "../sacredBharatGroupMembershipMigration.js";
import type * as sacredBharatGroups from "../sacredBharatGroups.js";
import type * as sacredBharatLeaderboard from "../sacredBharatLeaderboard.js";
import type * as sacredBharatLeaderboardRankMigration from "../sacredBharatLeaderboardRankMigration.js";
import type * as sacredBharatReturnContracts from "../sacredBharatReturnContracts.js";
import type * as testSupport_runtimeContracts from "../testSupport/runtimeContracts.js";
import type * as travelBatchSummaryMigration from "../travelBatchSummaryMigration.js";
import type * as trips from "../trips.js";
import type * as userProfiles from "../userProfiles.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  _exportSurface: typeof _exportSurface;
  _runtimeModules: typeof _runtimeModules;
  aiRuntime: typeof aiRuntime;
  auth: typeof auth;
  authAccountLinking: typeof authAccountLinking;
  authEmailDeliveries: typeof authEmailDeliveries;
  authEmailDeliveryIntents: typeof authEmailDeliveryIntents;
  authIdentityMigration: typeof authIdentityMigration;
  authSync: typeof authSync;
  bookings: typeof bookings;
  "crm/activity": typeof crm_activity;
  "crm/approvals": typeof crm_approvals;
  "crm/closedLeadStageMigration": typeof crm_closedLeadStageMigration;
  "crm/commandReceipts": typeof crm_commandReceipts;
  "crm/commercialFileActions": typeof crm_commercialFileActions;
  "crm/commercialFilePolicy": typeof crm_commercialFilePolicy;
  "crm/commercialFilePurge": typeof crm_commercialFilePurge;
  "crm/commercialFiles": typeof crm_commercialFiles;
  "crm/commercialRecordChain": typeof crm_commercialRecordChain;
  "crm/commercialRecordChainReads": typeof crm_commercialRecordChainReads;
  "crm/confirmedOffer": typeof crm_confirmedOffer;
  "crm/contractingPipelineCommands": typeof crm_contractingPipelineCommands;
  "crm/contractingPipelinePolicy": typeof crm_contractingPipelinePolicy;
  "crm/customerAttributionMigration": typeof crm_customerAttributionMigration;
  "crm/dashboard": typeof crm_dashboard;
  "crm/documentPreview": typeof crm_documentPreview;
  "crm/documentPreviewActions": typeof crm_documentPreviewActions;
  "crm/documentPreviewArtifact": typeof crm_documentPreviewArtifact;
  "crm/documentPreviewAudit": typeof crm_documentPreviewAudit;
  "crm/documentPreviewContract": typeof crm_documentPreviewContract;
  "crm/documentPreviewHttp": typeof crm_documentPreviewHttp;
  "crm/documentPreviewLifecycle": typeof crm_documentPreviewLifecycle;
  "crm/documentPreviewRollout": typeof crm_documentPreviewRollout;
  "crm/documentPreviewSource": typeof crm_documentPreviewSource;
  "crm/documentPreviewToken": typeof crm_documentPreviewToken;
  "crm/e2eAssertions": typeof crm_e2eAssertions;
  "crm/e2eFixtures": typeof crm_e2eFixtures;
  "crm/e2eRunOwnership": typeof crm_e2eRunOwnership;
  "crm/e2eSeed": typeof crm_e2eSeed;
  "crm/e2eSeedActions": typeof crm_e2eSeedActions;
  "crm/e2eStaffProfiles": typeof crm_e2eStaffProfiles;
  "crm/expenseApprovalWorkflow": typeof crm_expenseApprovalWorkflow;
  "crm/expenseAttachmentActions": typeof crm_expenseAttachmentActions;
  "crm/expenseAttachments": typeof crm_expenseAttachments;
  "crm/expenseCommands": typeof crm_expenseCommands;
  "crm/expenseLifecycle": typeof crm_expenseLifecycle;
  "crm/expenseLifecycleMigration": typeof crm_expenseLifecycleMigration;
  "crm/expenseMaterialIntegrity": typeof crm_expenseMaterialIntegrity;
  "crm/expensePolicy": typeof crm_expensePolicy;
  "crm/expenseReads": typeof crm_expenseReads;
  "crm/expenseScope": typeof crm_expenseScope;
  "crm/fileReturnContracts": typeof crm_fileReturnContracts;
  "crm/fileValidation": typeof crm_fileValidation;
  "crm/finance": typeof crm_finance;
  "crm/financeMetricSync": typeof crm_financeMetricSync;
  "crm/financeOverviewReads": typeof crm_financeOverviewReads;
  "crm/financeTicketingReturnContracts": typeof crm_financeTicketingReturnContracts;
  "crm/financeValidators": typeof crm_financeValidators;
  "crm/flightImports": typeof crm_flightImports;
  "crm/importActions": typeof crm_importActions;
  "crm/importBatchPolicy": typeof crm_importBatchPolicy;
  "crm/importProcessor": typeof crm_importProcessor;
  "crm/importReturnContracts": typeof crm_importReturnContracts;
  "crm/importRowValidators": typeof crm_importRowValidators;
  "crm/importRows": typeof crm_importRows;
  "crm/importWorkerPolicy": typeof crm_importWorkerPolicy;
  "crm/imports": typeof crm_imports;
  "crm/inboundQueryIntents": typeof crm_inboundQueryIntents;
  "crm/invoiceCommands": typeof crm_invoiceCommands;
  "crm/invoiceOutstandingPolicy": typeof crm_invoiceOutstandingPolicy;
  "crm/invoiceOutstandingProjection": typeof crm_invoiceOutstandingProjection;
  "crm/invoiceReads": typeof crm_invoiceReads;
  "crm/jobCardChecklist": typeof crm_jobCardChecklist;
  "crm/jobCardChecklistCommands": typeof crm_jobCardChecklistCommands;
  "crm/jobCardCommandCenter": typeof crm_jobCardCommandCenter;
  "crm/jobCardCommands": typeof crm_jobCardCommands;
  "crm/jobCardConstants": typeof crm_jobCardConstants;
  "crm/jobCardCreation": typeof crm_jobCardCreation;
  "crm/jobCardDeletion": typeof crm_jobCardDeletion;
  "crm/jobCardNotifications": typeof crm_jobCardNotifications;
  "crm/jobCardReads": typeof crm_jobCardReads;
  "crm/jobCardRelations": typeof crm_jobCardRelations;
  "crm/jobCardTravelBatchCommands": typeof crm_jobCardTravelBatchCommands;
  "crm/jobCardVisibility": typeof crm_jobCardVisibility;
  "crm/jobCards": typeof crm_jobCards;
  "crm/leave": typeof crm_leave;
  "crm/leaveApprovers": typeof crm_leaveApprovers;
  "crm/leaveLapse": typeof crm_leaveLapse;
  "crm/leaveMatrixData": typeof crm_leaveMatrixData;
  "crm/leavePolicy": typeof crm_leavePolicy;
  "crm/lib": typeof crm_lib;
  "crm/lib/activity": typeof crm_lib_activity;
  "crm/lib/bulkOps": typeof crm_lib_bulkOps;
  "crm/lib/codes": typeof crm_lib_codes;
  "crm/lib/documentPreviewImageSafety": typeof crm_lib_documentPreviewImageSafety;
  "crm/lib/e2eAuth": typeof crm_lib_e2eAuth;
  "crm/lib/e2eOwnership": typeof crm_lib_e2eOwnership;
  "crm/lib/inboundIntentPreparation": typeof crm_lib_inboundIntentPreparation;
  "crm/lib/leavePolicy": typeof crm_lib_leavePolicy;
  "crm/lib/majorCapabilityPreparation": typeof crm_lib_majorCapabilityPreparation;
  "crm/lib/notifications": typeof crm_lib_notifications;
  "crm/lib/operationalAdminAccess": typeof crm_lib_operationalAdminAccess;
  "crm/lib/operationalControls": typeof crm_lib_operationalControls;
  "crm/lib/operationalTargetIdentity": typeof crm_lib_operationalTargetIdentity;
  "crm/lib/portalFileDownloadLimit": typeof crm_lib_portalFileDownloadLimit;
  "crm/lib/portalFileDownloadPolicy": typeof crm_lib_portalFileDownloadPolicy;
  "crm/lib/presentation": typeof crm_lib_presentation;
  "crm/lib/productionTestExecution": typeof crm_lib_productionTestExecution;
  "crm/lib/productionTestRecipes": typeof crm_lib_productionTestRecipes;
  "crm/lib/recordScope": typeof crm_lib_recordScope;
  "crm/lib/rolePolicy": typeof crm_lib_rolePolicy;
  "crm/lib/staffAccess": typeof crm_lib_staffAccess;
  "crm/lib/validators": typeof crm_lib_validators;
  "crm/listSearch": typeof crm_listSearch;
  "crm/metricAggregates": typeof crm_metricAggregates;
  "crm/metricDirty": typeof crm_metricDirty;
  "crm/metricProjection": typeof crm_metricProjection;
  "crm/metricTypes": typeof crm_metricTypes;
  "crm/miscReturnContracts": typeof crm_miscReturnContracts;
  "crm/navShortcuts": typeof crm_navShortcuts;
  "crm/notificationCleanup": typeof crm_notificationCleanup;
  "crm/notificationEmailConfig": typeof crm_notificationEmailConfig;
  "crm/notificationEmailDelivery": typeof crm_notificationEmailDelivery;
  "crm/notificationEmailDetails": typeof crm_notificationEmailDetails;
  "crm/notificationEmailLedger": typeof crm_notificationEmailLedger;
  "crm/notificationEmails": typeof crm_notificationEmails;
  "crm/notificationPaths": typeof crm_notificationPaths;
  "crm/notificationReads": typeof crm_notificationReads;
  "crm/notificationSummary": typeof crm_notificationSummary;
  "crm/notificationUnreadProjection": typeof crm_notificationUnreadProjection;
  "crm/notificationUnreadProjectionMigration": typeof crm_notificationUnreadProjectionMigration;
  "crm/operationTimePolicy": typeof crm_operationTimePolicy;
  "crm/operationalSnapshots": typeof crm_operationalSnapshots;
  "crm/operationsReturnContracts": typeof crm_operationsReturnContracts;
  "crm/ops": typeof crm_ops;
  "crm/paginationPolicy": typeof crm_paginationPolicy;
  "crm/passengerExportCleanup": typeof crm_passengerExportCleanup;
  "crm/passengerExportFunctionReferences": typeof crm_passengerExportFunctionReferences;
  "crm/passengerExportOperations": typeof crm_passengerExportOperations;
  "crm/passengerExportPolicy": typeof crm_passengerExportPolicy;
  "crm/passengerExportSource": typeof crm_passengerExportSource;
  "crm/passengerExportSourceContract": typeof crm_passengerExportSourceContract;
  "crm/passengerExportWorkbook": typeof crm_passengerExportWorkbook;
  "crm/passengerExportWorker": typeof crm_passengerExportWorker;
  "crm/passengerImportCommit": typeof crm_passengerImportCommit;
  "crm/passengerImportOperations": typeof crm_passengerImportOperations;
  "crm/passengerImportReceipts": typeof crm_passengerImportReceipts;
  "crm/passengerImportRows": typeof crm_passengerImportRows;
  "crm/passengerKindPolicy": typeof crm_passengerKindPolicy;
  "crm/passport": typeof crm_passport;
  "crm/passportActions": typeof crm_passportActions;
  "crm/passportExpiry": typeof crm_passportExpiry;
  "crm/passportUploadTickets": typeof crm_passportUploadTickets;
  "crm/passportUploadValidation": typeof crm_passportUploadValidation;
  "crm/peopleWorkflowReturnContracts": typeof crm_peopleWorkflowReturnContracts;
  "crm/pnrCleanup": typeof crm_pnrCleanup;
  "crm/pnrCommands": typeof crm_pnrCommands;
  "crm/pnrReads": typeof crm_pnrReads;
  "crm/productionTestLab": typeof crm_productionTestLab;
  "crm/proposalAttachmentActions": typeof crm_proposalAttachmentActions;
  "crm/proposalAttachmentSummary": typeof crm_proposalAttachmentSummary;
  "crm/proposalAttachments": typeof crm_proposalAttachments;
  "crm/proposalDocument": typeof crm_proposalDocument;
  "crm/proposalDocumentState": typeof crm_proposalDocumentState;
  "crm/proposalHandoffCommands": typeof crm_proposalHandoffCommands;
  "crm/proposalLinkProjection": typeof crm_proposalLinkProjection;
  "crm/proposalReads": typeof crm_proposalReads;
  "crm/proposalRelationSummary": typeof crm_proposalRelationSummary;
  "crm/proposalRelations": typeof crm_proposalRelations;
  "crm/proposalReturnContracts": typeof crm_proposalReturnContracts;
  "crm/proposalVisibility": typeof crm_proposalVisibility;
  "crm/proposalWriteCommands": typeof crm_proposalWriteCommands;
  "crm/proposals": typeof crm_proposals;
  "crm/queries": typeof crm_queries;
  "crm/queryAttachmentActions": typeof crm_queryAttachmentActions;
  "crm/queryAttachments": typeof crm_queryAttachments;
  "crm/queryCommands": typeof crm_queryCommands;
  "crm/queryCommercialProjection": typeof crm_queryCommercialProjection;
  "crm/queryCreation": typeof crm_queryCreation;
  "crm/queryDeletion": typeof crm_queryDeletion;
  "crm/queryNotifications": typeof crm_queryNotifications;
  "crm/queryReads": typeof crm_queryReads;
  "crm/queryStatusPolicy": typeof crm_queryStatusPolicy;
  "crm/queryTeamAssignment": typeof crm_queryTeamAssignment;
  "crm/queryValidators": typeof crm_queryValidators;
  "crm/rateLimitMaintenance": typeof crm_rateLimitMaintenance;
  "crm/referenceTimePolicy": typeof crm_referenceTimePolicy;
  "crm/recoveryCenter": typeof crm_recoveryCenter;
  "crm/reports": typeof crm_reports;
  "crm/returnContracts": typeof crm_returnContracts;
  "crm/salesPipelineCommands": typeof crm_salesPipelineCommands;
  "crm/salesPipelinePolicy": typeof crm_salesPipelinePolicy;
  "crm/savedViews": typeof crm_savedViews;
  "crm/seatCommands": typeof crm_seatCommands;
  "crm/seatReads": typeof crm_seatReads;
  "crm/settings": typeof crm_settings;
  "crm/staff": typeof crm_staff;
  "crm/staffAction": typeof crm_staffAction;
  "crm/staffImport": typeof crm_staffImport;
  "crm/staffSettingsReturnContracts": typeof crm_staffSettingsReturnContracts;
  "crm/staffWorkbookUpdates": typeof crm_staffWorkbookUpdates;
  "crm/storageReferences": typeof crm_storageReferences;
  "crm/ticketCommands": typeof crm_ticketCommands;
  "crm/ticketReads": typeof crm_ticketReads;
  "crm/ticketStatusPolicy": typeof crm_ticketStatusPolicy;
  "crm/ticketing": typeof crm_ticketing;
  "crm/ticketingAssignmentPolicy": typeof crm_ticketingAssignmentPolicy;
  "crm/ticketingDashboardReads": typeof crm_ticketingDashboardReads;
  "crm/ticketingIntakePolicy": typeof crm_ticketingIntakePolicy;
  "crm/ticketingPresentation": typeof crm_ticketingPresentation;
  "crm/ticketingValidators": typeof crm_ticketingValidators;
  "crm/travelBatchPolicy": typeof crm_travelBatchPolicy;
  "crm/travellers": typeof crm_travellers;
  "crm/validateReturnContract": typeof crm_validateReturnContract;
  "crm/visa": typeof crm_visa;
  "crm/workflowNudgeRun": typeof crm_workflowNudgeRun;
  "crm/workflowNudges": typeof crm_workflowNudges;
  crons: typeof crons;
  customerConfirmedTrips: typeof customerConfirmedTrips;
  customerJourneyModel: typeof customerJourneyModel;
  e2eDeploymentIdentity: typeof e2eDeploymentIdentity;
  http: typeof http;
  "lib/aiRateLimit": typeof lib_aiRateLimit;
  "lib/authEmailDelivery": typeof lib_authEmailDelivery;
  "lib/authEmailHtml": typeof lib_authEmailHtml;
  "lib/authIdentity": typeof lib_authIdentity;
  "lib/authIdentityMigration": typeof lib_authIdentityMigration;
  "lib/authOriginPolicy": typeof lib_authOriginPolicy;
  "lib/authSync": typeof lib_authSync;
  "lib/betterAuthEmail": typeof lib_betterAuthEmail;
  "lib/betterAuthLookup": typeof lib_betterAuthLookup;
  "lib/bootstrapAuthority": typeof lib_bootstrapAuthority;
  "lib/customerIdentityAccess": typeof lib_customerIdentityAccess;
  "lib/emailConfig": typeof lib_emailConfig;
  "lib/encryption": typeof lib_encryption;
  "lib/formatDate": typeof lib_formatDate;
  "lib/importContractValidators": typeof lib_importContractValidators;
  "lib/passportPayloadCrypto": typeof lib_passportPayloadCrypto;
  "lib/paymentMutationAuth": typeof lib_paymentMutationAuth;
  "lib/profileFallback": typeof lib_profileFallback;
  "lib/rateLimiterComponent": typeof lib_rateLimiterComponent;
  "lib/roomTypeValidators": typeof lib_roomTypeValidators;
  "lib/roomTypes": typeof lib_roomTypes;
  "lib/runtimeValues": typeof lib_runtimeValues;
  "lib/sacredBharatAliases": typeof lib_sacredBharatAliases;
  "lib/sacredBharatGroups": typeof lib_sacredBharatGroups;
  "lib/sacredBharatGuestMerge": typeof lib_sacredBharatGuestMerge;
  "lib/sacredBharatInvites": typeof lib_sacredBharatInvites;
  "lib/sacredBharatLeaderboard": typeof lib_sacredBharatLeaderboard;
  "lib/sacredBharatLeaderboardRank": typeof lib_sacredBharatLeaderboardRank;
  "lib/sacredBharatScoring": typeof lib_sacredBharatScoring;
  "lib/staffAuthRepair": typeof lib_staffAuthRepair;
  "lib/travelBatchSummary": typeof lib_travelBatchSummary;
  migrationAuth: typeof migrationAuth;
  migrations: typeof migrations;
  operationalScheduledJobs: typeof operationalScheduledJobs;
  publicReturnContracts: typeof publicReturnContracts;
  sacredBharat: typeof sacredBharat;
  sacredBharatEditionEvents: typeof sacredBharatEditionEvents;
  sacredBharatGroupMembershipMigration: typeof sacredBharatGroupMembershipMigration;
  sacredBharatGroups: typeof sacredBharatGroups;
  sacredBharatLeaderboard: typeof sacredBharatLeaderboard;
  sacredBharatLeaderboardRankMigration: typeof sacredBharatLeaderboardRankMigration;
  sacredBharatReturnContracts: typeof sacredBharatReturnContracts;
  "testSupport/runtimeContracts": typeof testSupport_runtimeContracts;
  travelBatchSummaryMigration: typeof travelBatchSummaryMigration;
  trips: typeof trips;
  userProfiles: typeof userProfiles;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  betterAuth: import("../betterAuth/_generated/component.js").ComponentApi<"betterAuth">;
  rateLimiter: import("@convex-dev/rate-limiter/_generated/component.js").ComponentApi<"rateLimiter">;
  sacredBharatLeaderboardRanks: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"sacredBharatLeaderboardRanks">;
};
