export const PASSENGER_EXPORT_HEADERS = [
  "NO",
  "",
  "SURNAME",
  "Name As per Govt. ID Proof",
  "Gender",
  "Passport no ",
  "Date of Birth",
  "Passport Issus date",
  "Passport Exp",
  "Meal Preference",
  "Contact No.",
  "International fare",
  "International PNR",
  "VENDOR",
  "Domestic ticket",
  "Domestic PNR",
  "VENDOR",
  "Travel Batch",
];

export const FLIGHT_EXPORT_HEADER = [
  "Date",
  "Airline",
  "Flight No",
  "Depart",
  "from",
  "Arrive",
  "at",
  "Duration",
  "Transit",
];

export const TRAVELLER_MASTER_EXPORT_HEADERS = [
  "S.No",
  "Branch ",
  "Branch Code",
  "Dealer Name",
  "Gender",
  "SURNAME",
  "GIVEN NAME",
  "Passport Number",
  "Passport Issue date",
  "Passport expiry date",
  "Date of Birth As per passport",
  "Place of Issue",
  "Contact Number",
  "Email id",
  "Base Location",
  "Food Preference",
  "Hub",
  "Airlines",
  "Travel Batch",
  "",
];

export const ROOMING_EXPORT_HEADERS = [
  "Sl.no.",
  "Dealer Name",
  "Gender",
  "SURNAME",
  "GIVEN NAME",
  "ROOMING Category",
  "REMARKS",
  "Passport Number",
  "Passport Issue date",
  "Passport expiry date",
  "Date of Birth As per passport",
  "Place of Issue",
  "Contact Number",
  "Email id",
  "Meal",
  "Hub",
  "Airlines International",
  "Airlines Domestic ",
  "Travel Batch",
  "",
];

export const PASSPORT_EXPORT_HEADERS = [
  "Sl.no.",
  "Dealer Name",
  "Gender",
  "SURNAME",
  "GIVEN NAME",
  "Passport Number",
  "Passport Issue date",
  "Passport expiry date",
  "PP Valid for Travel Yes /No",
  "Date of Birth As per passport",
  "Place of Issue",
  "REMARKS:  Expiry PP / Under Renewal",
  "Contact Number",
  "Travel Batch",
];

export const VISA_EXPORT_HEADERS = [
  "Sl.no.",
  "Dealer Name",
  "Gender",
  "SURNAME",
  "GIVEN NAME",
  "Passport Number",
  "Passport Issue date",
  "Passport expiry date",
  "PP Valid for Travel Yes /No",
  "Date of Birth As per passport",
  "Place of Issue",
  "REMARKS:  Expiry PP / Under Renewal",
  "Contact Number",
  "Biometric Required",
  "Date of Appointmemt ",
  "VFS Center ",
  "Status Of Visa ",
  "Company paid/ Self Paid",
  "Amount",
  "Remarks ",
  "Travel Batch",
];
