export function toPassengerImportInput(row) {
  return {
    id: row.id,
    sourceSheet: row.sourceSheet,
    sourceRowNumber: row.sourceRowNumber,
    importKind: row.importKind,
    importKey: row.importKey,
    travelBatchId: row.travelBatchId,
    travelBatchReference: row.travelBatchReference,
    fullName: row.fullName,
    surname: row.surname,
    givenName: row.givenName,
    travelHub: row.travelHub,
    foodPreference: row.foodPreference,
    guestType: row.guestType,
    paymentType: row.paymentType,
    roomType: row.roomType,
    visaRequired: row.visaRequired,
    domesticTravelRequired: row.domesticTravelRequired,
    passportStatus: row.passportStatus,
    specialRequests: row.specialRequests,
    sourceDealerCode: row.sourceDealerCode,
    sourceDealerName: row.sourceDealerName,
    sourceDescription: row.sourceDescription,
    sourceSoName: row.sourceSoName,
    sourceRsoName: row.sourceRsoName,
    sourceGroup: row.sourceGroup,
    gender: row.gender,
    contactNo: row.contactNo,
    hotelAllocation: row.hotelAllocation,
    visaStatus: row.visaStatus || undefined,
    biometricAppointmentDate: row.biometricAppointmentDate,
    visaNotes: row.visaNotes,
    passport: {
      number: row.passport?.number,
      dateOfBirth: row.passport?.dateOfBirth,
      issueDate: row.passport?.issueDate,
      expiryDate: row.passport?.expiryDate,
      nationality: row.passport?.nationality,
    },
    ticketing: row.ticketing,
  };
}
