import { PORTAL_PERMISSIONS as P } from "@/lib/portal/constants";

export const TRAVEL_BATCH_MODAL = "travelBatch";

export const SPREADSHEET_MODALS = [
  "passengerImport",
  "flightImport",
  "passengerExport",
  "flightExport",
  "travellerImport",
  "travellerExport",
  "roomingImport",
  "roomingExport",
  "passportImport",
  "passportExport",
  "visaImport",
  "visaExport",
];

export const VIEW_META = {
  dashboard: {
    title: "Dashboard",
    subtitle: "",
    permission: P.VIEW_DASHBOARD,
  },
  queries: {
    title: "All Sales Queries",
    subtitle: "Manage incoming MICE, group travel, FIT, B2B, cement, and spiritual enquiries.",
    permission: P.VIEW_QUERIES,
  },
  pipeline: {
    title: "Pipeline View",
    subtitle: "Track query movement from contracting to confirmed or lost.",
    permission: P.VIEW_QUERIES,
  },
  proposals: {
    title: "Proposals",
    subtitle: "Create, cost, and send proposals linked to active queries.",
    permission: P.VIEW_PROPOSALS,
  },
  contracting: {
    title: "Contracting Dashboard",
    subtitle: "Assign contracting SPOCs and move proposals through contracting statuses.",
    permission: P.VIEW_CONTRACTING,
  },
  "accounts-job-cards": {
    title: "Accounts / Job Card Creation",
    subtitle: "Create Job Card numbers only after order confirmation.",
    permission: P.MANAGE_JOB_CARDS,
  },
  "job-cards": {
    title: "Job Cards",
    subtitle: "Operational file control, progress, and pre-departure checklist status.",
    permission: P.VIEW_JOB_CARDS,
  },
  travellers: {
    title: "Traveller Master Sheet",
    subtitle:
      "Guest details, hubs, food preferences, rooming, visa, ticket, and TM calling status.",
    permission: P.VIEW_TRAVELLERS,
  },
  passport: {
    title: "Passport Documents",
    subtitle: "Upload, encrypt, and manage traveller passport scans.",
    permission: P.VIEW_VISA,
  },
  visa: {
    title: "Visa Tracking",
    subtitle:
      "Checklist, appointments, submission, approval, rejection, and re-application tracking.",
    permission: P.VIEW_VISA,
  },
  ticketing: {
    title: "Ticket Dashboard",
    subtitle: "Ticket status summary across active Job Cards.",
    permission: P.VIEW_TICKETING,
  },
  flights: {
    title: "Flights & PNR",
    subtitle: "Manage PNRs, routes, fare types, group seats, and airline records.",
    permission: P.VIEW_TICKETING,
  },
  "seat-allocation": {
    title: "Seat Allocation",
    subtitle: "Manual stored seat assignments, holds, and blocks.",
    permission: P.VIEW_TICKETING,
  },
  tickets: {
    title: "All Tickets",
    subtitle: "Issue, reissue, cancellation, name correction, and refund tracking.",
    permission: P.VIEW_TICKETING,
  },
  hotels: {
    title: "Hotel / Rooming List",
    subtitle: "Hotel arrangements, rooming, special instructions, and ground planning.",
    permission: P.VIEW_OPERATIONS,
  },
  "tour-managers": {
    title: "Tour Managers",
    subtitle: "TM assignment, calling status, availability, and active tour visibility.",
    permission: P.VIEW_TOUR_MANAGERS,
  },
  finance: {
    title: "Finance",
    subtitle: "Fund projections, invoices, received amounts, balances, and closure status.",
    permission: P.VIEW_FINANCE,
  },
  expenses: {
    title: "Expense Management",
    subtitle: "Tour-wise expenses, approval, and reimbursement tracking.",
    permission: P.VIEW_EXPENSES,
  },
  approvals: {
    title: "Approvals",
    subtitle: "Unified approval queue for expenses and finance handoffs.",
    permission: P.VIEW_APPROVALS,
  },
  reports: {
    title: "Reports",
    subtitle: "Revenue, headcount, and conversion snapshots for leadership review.",
    permission: P.VIEW_REPORTS,
  },
  team: {
    title: "Team Directory",
    subtitle: "Read-only staff directory by department, role, and location.",
    permission: P.VIEW_TEAM,
  },
  "employees-on-leave": {
    title: "Employees on Leave",
    subtitle: "Leave requests, approvals, and team availability.",
    permission: P.VIEW_LEAVE,
  },
  activity: {
    title: "Notifications / Activity Log",
    subtitle: "Audit trail for CRM status changes and workflow triggers.",
    permission: P.VIEW_ACTIVITY,
  },
  settings: {
    title: "Settings / Dropdown Management",
    subtitle: "Staff allowlist and workflow dropdown reference values.",
    permission: P.MANAGE_STAFF,
  },
};

export const INITIAL_FORM = {
  clientName: "",
  contactPerson: "",
  contactMobile: "",
  destination: "",
  paxCount: "1",
  travelStartDate: "",
  travelEndDate: "",
  queryType: "MICE",
  travelType: "International Travel",
  budgetAmount: "",
  source: "Client",
  leadStage: "Inquiry",
  salesOwnerName: "",
  notes: "",
  queryCode: "",
  queryId: "",
  queryIds: [],
  proposalId: "",
  landCostPerPax: "",
  airfarePerPax: "",
  visaCostPerPax: "",
  sellingPrice: "",
  costPrice: "",
  taxRate: "",
  expenseType: "jobCard",
  itinerarySummary: "",
  ownerName: "",
  salesStatus: "Proposal in discussion",
  contractingStatus: "Proposal in progress",
  lostReason: "Price",
  contractingLandCost: "",
  contractingAirlinesCost: "",
  contractingVisaCost: "",
  approxMargin: "",
  confirmedPax: "1",
  roomCount: "",
  tourManagerName: "",
  batchReference: "",
  contractingOwnerId: "",
  contractingOwnerName: "",
  operationsOwnerId: "",
  operationsOwnerName: "",
  ticketingOwnerId: "",
  ticketingOwnerName: "",
  jobCardId: "",
  travelBatchId: "",
  fullName: "",
  surname: "",
  givenName: "",
  travelHub: "",
  travelDate: "",
  guestCompanions: "",
  foodPreference: "Veg",
  gender: "",
  guestType: "Employee",
  paymentType: "Company Paid",
  roomType: "Twin",
  visaRequired: "Yes",
  passportStatus: "Pending",
  hotelAllocation: "",
  domesticTravelRequired: "No",
  biometricAppointmentDate: "",
  extensionOfTour: "No",
  arrivingEarly: "No",
  visaRecordId: "",
  visaStatus: "Checklist Shared",
  appointmentDate: "",
  pnrCode: "",
  airline: "",
  route: "",
  fareType: "",
  totalSeats: "1",
  travellerId: "",
  pnrId: "",
  ticketNumber: "",
  ticketType: "FIT Ticket",
  ticketStatus: "Issued",
  cabinClass: "Economy",
  seatPreference: "",
  seatNumber: "",
  seatStatus: "Assigned",
  hotelName: "",
  city: "",
  checkInDate: "",
  checkOutDate: "",
  staffId: "",
  staffName: "",
  staffEmail: "",
  staffRoles: ["Sales"],
  staffActive: true,
  joiningDate: "",
  employmentStatus: "Confirmed",
  confirmationDate: "",
  leavePolicyGroup: "",
  leaveHeadApproverId: "",
  reportingManagerStaffId: "",
  reportingManagerName: "",
  maternityEventsUsed: "0",
  paternityEventsUsed: "0",
  marriageLeaveUsed: false,
  invoiceNumber: "",
  expectedAmount: "",
  receivedAmount: "",
  dueDate: "",
  category: "",
  expenseDate: "",
  particulars: "",
  currency: "INR",
  cardAmount: "",
  cashAmount: "",
  epayAmount: "",
  amount: "",
  paidBy: "",
  department: "",
  leaveType: "Casual",
  startDate: "",
  endDate: "",
  reason: "",
  status: "Pending",
  entityId: "",
  approvalId: "",
  approvalStatus: "Rejected",
  decisionNote: "",
  salesDecision: "Proposal in discussion",
  ticketingScope: "",
  travelInBatches: "No",
  batchingNotes: "",
  ticketingStaffId: "",
  staffFunction: "",
  mobile: "",
  location: "",
};

/** @param {{ job?: Record<string, unknown>, batch?: Record<string, unknown> }} source */
export function buildTravelBatchModalInitial({ job, batch } = {}) {
  if (batch) {
    return {
      entityId: batch.id,
      jobCardId: batch.jobCardId,
      batchReference: batch.batchReference || "",
      destination: batch.destination || "",
      confirmedPax: String(batch.confirmedPax ?? ""),
      roomCount: String(batch.roomCount ?? ""),
      travelStartDate: batch.travelStartDate || "",
      travelEndDate: batch.travelEndDate || "",
      contractingOwnerId: batch.contractingOwnerId || "",
      contractingOwnerName: batch.contractingOwnerName || "",
      operationsOwnerId: batch.operationsOwnerId || "",
      operationsOwnerName: batch.operationsOwnerName || "",
      ticketingOwnerId: batch.ticketingOwnerId || "",
      ticketingOwnerName: batch.ticketingOwnerName || "",
      tourManagerName: batch.tourManagerName || "",
      status: batch.status || "Open",
    };
  }
  if (job) {
    return {
      jobCardId: job.id,
      destination: job.destination || "",
      confirmedPax: String(job.confirmedPax ?? ""),
      roomCount: String(job.roomCount ?? ""),
      travelStartDate: job.travelStartDate || "",
      travelEndDate: job.travelEndDate || "",
      contractingOwnerId: job.contractingOwnerId || "",
      contractingOwnerName: job.contractingOwnerName || "",
      operationsOwnerId: job.operationsOwnerId || "",
      operationsOwnerName: job.operationsOwnerName || "",
      ticketingOwnerId: job.ticketingOwnerId || "",
      ticketingOwnerName: job.ticketingOwnerName || "",
      tourManagerName: job.tourManagerName || "",
      status: job.status || "Open",
    };
  }
  return {};
}

/** @param {Record<string, unknown>} batch */
export function formatTravelBatchOwnerSummary(batch) {
  const owners = [
    batch.contractingOwnerName,
    batch.operationsOwnerName,
    batch.ticketingOwnerName,
  ].filter(Boolean);
  return owners.length > 0 ? owners.join(" · ") : "Unassigned";
}
