import {
  Armchair,
  BadgeCheck,
  BedDouble,
  BookOpen,
  CalendarDays,
  ChartNoAxesCombined,
  ClipboardCheck,
  ClipboardList,
  Contact,
  ContactRound,
  FileText,
  Gauge,
  Handshake,
  History,
  Inbox,
  Kanban,
  Landmark,
  LayoutDashboard,
  type LucideIcon,
  Plane,
  ReceiptIndianRupee,
  RefreshCcw,
  Settings2,
  Stamp,
  TicketCheck,
  UsersRound,
  WalletCards,
} from "lucide-react";

export const PORTAL_NAV_ICONS = {
  "/portal": LayoutDashboard,
  "/portal/accounts/job-cards": Landmark,
  "/portal/activity": History,
  "/portal/approvals": BadgeCheck,
  "/portal/contracting": Handshake,
  "/portal/employees-on-leave": CalendarDays,
  "/portal/expenses": ReceiptIndianRupee,
  "/portal/finance": WalletCards,
  "/portal/flights": Plane,
  "/portal/hotels": BedDouble,
  "/portal/inbound-leads": Inbox,
  "/portal/job-cards": ClipboardCheck,
  "/portal/passport": BookOpen,
  "/portal/pipeline": Kanban,
  "/portal/proposals": FileText,
  "/portal/queries": ClipboardList,
  "/portal/recovery": RefreshCcw,
  "/portal/reports": ChartNoAxesCombined,
  "/portal/seat-allocation": Armchair,
  "/portal/settings": Settings2,
  "/portal/team": Contact,
  "/portal/ticketing": Gauge,
  "/portal/tickets": TicketCheck,
  "/portal/tour-managers": ContactRound,
  "/portal/travellers": UsersRound,
  "/portal/visa": Stamp,
} satisfies Record<string, LucideIcon>;
