import type { BoothLanguage } from "./contracts";

const en = {
  addPhoto: "2. Add your photo",
  adjust: "Adjust your cutout",
  artworkNote: "Destination scenes are creative illustrations.",
  camera: "Take a photo",
  cancel: "Cancel",
  cancelled: "Cancelled. Your photo is still here.",
  checking: "Checking whether the photo booth is open…",
  choosePhoto: "Choose a photo",
  chooseScene: "1. Choose your scene",
  closed: "The photo booth is closed",
  closedDuring: "The booth has closed. You can still download or share your ready photo.",
  closedHelp:
    "Thanks for being part of the moment. You can still discover your next journey with Citius Holidays.",
  continue: "Continue without saving",
  create: "Create my photo",
  cutout: "Destination cutout",
  cutoutError:
    "We couldn’t make a clear cutout. Try again, choose another photo, or select the whole-photo frame below.",
  cutoutHelp:
    "Replaces the background while keeping your faces and clothes. Check that everyone looks right.",
  downloaded: "Download requested. Check your downloads or save the image to your photos.",
  emptyPreview: "Your moment goes here",
  emptyPreviewHelp: "Add a photo to bring this scene to life.",
  enquiryHelp: "Optional. Opens a travel enquiry; nothing is sent until you submit the form.",
  explore: "Explore Citius Holidays",
  explorePilgrimage: "Explore pilgrimage journeys",
  firstLoad:
    "The first cutout downloads about 29 MB. It can take a moment on mobile data. The frame option needs no download of the cutout tool.",
  format: "Photo format",
  frame: "Whole-photo frame",
  frameHelp: "Keeps your entire photo, including its original background, inside a Citius frame.",
  home: "Citius Holidays home",
  horizontal: "Move left / right",
  intro: "Choose somewhere you love. Put yourself in the picture.",
  language: "Language / भाषा",
  loading: "Opening your photo…",
  noScenes: "New scenes are being prepared. Please try again shortly.",
  photoHelp:
    "Solo, couple or small family. Keep everyone visible. JPG, PNG or WebP, up to 12 MB. Convert HEIC to JPG first.",
  pilgrimage: "Pilgrimage",
  plan: "Plan a trip here",
  portrait: "Post · 4:5",
  preparing: "Preparing the cutout tool…",
  preview: "3. Make it yours",
  previewAlt: "Your Citius destination photo preview",
  previewHelp: "Your download will match this preview.",
  previousResult: "Previous ready photo",
  privacy: "Your photo stays on this device. Save it before leaving; there is no photo history.",
  privacyLink: "Policies & privacy",
  privileged:
    "Staff preview: your Admin or Director access lets you create photos while the event is closed.",
  processing: "Keeping the people, removing the background…",
  ready: "Your photo is ready. Save it before you leave.",
  renderError:
    "The preview couldn’t be prepared. Your photo is still here. Check your connection and retry.",
  rendering: "Preparing your preview…",
  resetPlacement: "Reset placement",
  retry: "Try again",
  retryCutout: "Retry cutout",
  retryPreview: "Retry preview",
  save: "Download photo",
  selected: "Selected",
  share: "Share photo",
  shareCancelled: "Sharing cancelled. Your photo is still ready to download or share.",
  shareFailed: "Share couldn’t open. Download your photo and share it from your gallery.",
  shareHandedOff: "Photo handed to your Share menu. Finish sharing in the app you choose.",
  shareHelp:
    "Choose an app in your phone’s Share menu. To post manually, download the photo and open your app.",
  shareUnavailable:
    "File sharing isn’t available in this browser. Download your photo, then open the app you want to post to.",
  sharing: "Opening Share…",
  size: "Size",
  sourceAlt: "Your selected photo, kept only on this device",
  startOver: "Start over",
  story: "Story · 9:16",
  title: "A photo. A place. Your moment.",
  travel: "Travel",
  unavailable: "We couldn’t check the photo booth. Please try again.",
  unsaved:
    "Save or share your photo first. Leaving or starting over removes it from this session. Continue without saving?",
  unsavedTitle: "Keep your photo?",
  uploadError:
    "We couldn’t open that photo. Choose a still JPG, PNG or WebP under 12 MB and 25 megapixels. Your previous photo is still here.",
  vertical: "Move up / down",
} as const;

const hi = {
  addPhoto: "2. अपनी तस्वीर जोड़ें",
  adjust: "कटआउट ठीक करें",
  artworkNote: "जगहों के दृश्य कलात्मक चित्रण हैं।",
  camera: "तस्वीर लें",
  cancel: "रद्द करें",
  cancelled: "रद्द कर दिया गया। आपकी तस्वीर यहीं है।",
  checking: "फ़ोटो बूथ खुला है या नहीं, जाँच रहे हैं…",
  choosePhoto: "तस्वीर चुनें",
  chooseScene: "1. अपनी जगह चुनें",
  closed: "फ़ोटो बूथ बंद है",
  closedDuring: "बूथ बंद हो गया है। तैयार तस्वीर अभी भी डाउनलोड या शेयर कर सकते हैं।",
  closedHelp: "इस पल का हिस्सा बनने के लिए धन्यवाद। Citius Holidays के साथ अपनी अगली यात्रा खोजें।",
  continue: "बिना सेव किए आगे बढ़ें",
  create: "मेरी तस्वीर बनाएँ",
  cutout: "जगह के साथ कटआउट",
  cutoutError: "साफ़ कटआउट नहीं बन सका। फिर कोशिश करें, दूसरी तस्वीर चुनें या नीचे पूरी तस्वीर का फ़्रेम चुनें।",
  cutoutHelp: "चेहरे और कपड़े वही रखकर पृष्ठभूमि बदलता है। जाँच लें कि सभी लोग सही दिख रहे हैं।",
  downloaded: "डाउनलोड शुरू किया गया। डाउनलोड फ़ोल्डर जाँचें या तस्वीर गैलरी में सेव करें।",
  emptyPreview: "यहाँ होगा आपका खास पल",
  emptyPreviewHelp: "इस जगह के साथ अपनी तस्वीर जोड़ें।",
  enquiryHelp: "वैकल्पिक। यात्रा के लिए पूछताछ फ़ॉर्म खुलेगा। फ़ॉर्म जमा करने से पहले कुछ नहीं भेजा जाता।",
  explore: "Citius Holidays की यात्राएँ देखें",
  explorePilgrimage: "तीर्थयात्राएँ देखें",
  firstLoad:
    "पहली बार कटआउट बनाने के लिए लगभग 29 MB डाउनलोड होता है। मोबाइल डेटा पर थोड़ा समय लग सकता है। फ़्रेम के लिए यह डाउनलोड ज़रूरी नहीं है।",
  format: "तस्वीर का आकार",
  frame: "पूरी तस्वीर का फ़्रेम",
  frameHelp: "आपकी पूरी तस्वीर और उसकी मूल पृष्ठभूमि Citius के फ़्रेम में रहती है।",
  home: "Citius Holidays मुख्य पृष्ठ",
  horizontal: "बाएँ / दाएँ करें",
  intro: "अपनी पसंद की जगह चुनें। तस्वीर में खुद को शामिल करें।",
  language: "Language / भाषा",
  loading: "आपकी तस्वीर खुल रही है…",
  noScenes: "नई जगहों की तस्वीरें तैयार हो रही हैं। थोड़ी देर बाद फिर कोशिश करें।",
  photoHelp:
    "अकेले, जोड़े या छोटे परिवार की तस्वीर। सभी लोग साफ़ दिखें। JPG, PNG या WebP, अधिकतम 12 MB। HEIC को पहले JPG में बदलें।",
  pilgrimage: "तीर्थयात्रा",
  plan: "यहाँ की यात्रा प्लान करें",
  portrait: "पोस्ट · 4:5",
  preparing: "कटआउट टूल तैयार हो रहा है…",
  preview: "3. अपना अंदाज़ दें",
  previewAlt: "आपकी Citius तस्वीर का प्रीव्यू",
  previewHelp: "डाउनलोड की गई तस्वीर इसी प्रीव्यू जैसी होगी।",
  previousResult: "पिछली तैयार तस्वीर",
  privacy: "आपकी तस्वीर इसी डिवाइस पर रहती है। जाने से पहले सेव करें; तस्वीरों का इतिहास नहीं रखा जाता।",
  privacyLink: "नीतियाँ और गोपनीयता",
  privileged: "स्टाफ़ प्रीव्यू: एडमिन या डायरेक्टर होने के कारण आप बूथ बंद होने पर भी तस्वीर बना सकते हैं।",
  processing: "लोगों को रखते हुए पृष्ठभूमि हटाई जा रही है…",
  ready: "आपकी तस्वीर तैयार है। जाने से पहले सेव कर लें।",
  renderError: "प्रीव्यू तैयार नहीं हो सका। आपकी तस्वीर यहीं है। इंटरनेट कनेक्शन जाँचकर फिर कोशिश करें।",
  rendering: "प्रीव्यू तैयार हो रहा है…",
  resetPlacement: "स्थिति रीसेट करें",
  retry: "फिर कोशिश करें",
  retryCutout: "कटआउट फिर बनाएँ",
  retryPreview: "प्रीव्यू फिर बनाएँ",
  save: "तस्वीर डाउनलोड करें",
  selected: "चयनित",
  share: "तस्वीर शेयर करें",
  shareCancelled: "शेयर करना रद्द किया गया। तस्वीर डाउनलोड या शेयर करने के लिए तैयार है।",
  shareFailed: "शेयर मेन्यू नहीं खुल सका। तस्वीर डाउनलोड करके गैलरी से शेयर करें।",
  shareHandedOff: "तस्वीर शेयर मेन्यू को दी गई है। चुने हुए ऐप में शेयर करना पूरा करें।",
  shareHelp: "फ़ोन के शेयर मेन्यू में ऐप चुनें। खुद पोस्ट करने के लिए तस्वीर डाउनलोड करके अपना ऐप खोलें।",
  shareUnavailable:
    "इस ब्राउज़र से फ़ाइल शेयर नहीं हो सकती। तस्वीर डाउनलोड करें, फिर अपने पसंद के ऐप में पोस्ट करें।",
  sharing: "शेयर मेन्यू खुल रहा है…",
  size: "आकार",
  sourceAlt: "आपकी चुनी हुई तस्वीर, केवल इसी डिवाइस पर",
  startOver: "फिर शुरू करें",
  story: "स्टोरी · 9:16",
  title: "एक तस्वीर। एक जगह। आपका पल।",
  travel: "घूमने की जगहें",
  unavailable: "फ़ोटो बूथ की स्थिति जाँच नहीं सके। फिर कोशिश करें।",
  unsaved: "पहले तस्वीर सेव या शेयर कर लें। जाने या फिर शुरू करने पर यह तस्वीर हट जाएगी। बिना सेव किए आगे बढ़ें?",
  unsavedTitle: "अपनी तस्वीर सेव करें?",
  uploadError:
    "यह तस्वीर नहीं खुल सकी। 12 MB और 25 मेगापिक्सल से छोटी JPG, PNG या WebP तस्वीर चुनें। पिछली तस्वीर यहीं है।",
  vertical: "ऊपर / नीचे करें",
} satisfies Record<keyof typeof en, string>;

export type BoothCopyKey = keyof typeof en;
export function boothCopy(language: BoothLanguage) {
  return language === "hi" ? hi : en;
}
