import type { BoothLanguage } from "./contracts";

const en = {
  addPhoto: "Add your photo",
  adjust: "Adjust your cutout",
  artworkNote: "Destination scenes are creative illustrations.",
  camera: "Take a photo",
  cancel: "Cancel",
  cancelled: "Cancelled. Your photo is still here.",
  checking: "Checking whether the photo booth is open…",
  choosePhoto: "Choose a photo",
  chooseScene: "Choose your scene",
  closed: "The photo booth is closed",
  closedDuring: "The booth has closed. You can still download or share your ready photo.",
  closedHelp: "You can still explore Citius trips using the links below.",
  continue: "Continue without saving",
  create: "Create my photo",
  cutout: "Replace background",
  cutoutError:
    "We couldn't remove the background. Try again, choose another photo, or keep the original photo.",
  downloaded: "Download requested. Check your downloads or save the image to your photos.",
  explore: "Explore Citius Holidays",
  explorePilgrimage: "Explore pilgrimage journeys",
  firstLoad: "First use downloads about 29 MB to remove the background.",
  format: "Photo format",
  frame: "Keep original photo",
  home: "Citius Holidays home",
  horizontal: "Move left / right",
  language: "Language / भाषा",
  loading: "Opening your photo…",
  noScenes: "No scenes are available. Please try again later.",
  photoHelp: "JPG, PNG or WebP, up to 12 MB. Convert HEIC to JPG first.",
  photoOptions: "Change photo or style",
  photoStyle: "Photo style",
  pilgrimage: "Pilgrimage",
  plan: "Plan a trip here",
  portrait: "Post · 4:5",
  preparing: "Preparing the cutout tool…",
  preview: "Preview your photo",
  previewAlt: "Your Citius destination photo preview",
  previousResult: "Previous ready photo",
  privacy: "Your photo stays on this device. Save it before leaving.",
  privacyLink: "Policies & privacy",
  privileged:
    "Staff preview: your Admin or Director access lets you create photos while the event is closed.",
  processing: "Keeping the people, removing the background…",
  renderError:
    "The preview couldn't be prepared. Your photo is still here. Check your connection and retry.",
  rendering: "Preparing your preview…",
  resetPlacement: "Reset placement",
  retry: "Try again",
  retryCutout: "Retry cutout",
  retryPreview: "Retry preview",
  save: "Download photo",
  selected: "Selected",
  share: "Share photo",
  shareCancelled: "Sharing cancelled. Your photo is still ready to download or share.",
  shareFailed: "Share couldn't open. Download your photo and share it from your gallery.",
  shareHandedOff: "Photo handed to your Share menu. Finish sharing in the app you choose.",
  shareUnavailable:
    "File sharing isn't available in this browser. Download your photo, then open the app you want to post to.",
  sharing: "Opening Share…",
  size: "Size",
  sourceAlt: "Your selected photo, kept only on this device",
  startOver: "Start over",
  story: "Story · 9:16",
  title: "Photo booth",
  travel: "Travel",
  unavailable: "We couldn't check the photo booth. Please try again.",
  unsaved:
    "Save or share your photo first. Leaving or starting over removes it from this session. Continue without saving?",
  unsavedTitle: "Keep your photo?",
  uploadError:
    "We couldn't open that photo. Choose a still JPG, PNG or WebP under 12 MB and 25 megapixels. Your previous photo is still here.",
  vertical: "Move up / down",
} as const;

const hi = {
  addPhoto: "अपनी तस्वीर जोड़ें",
  adjust: "कटआउट ठीक करें",
  artworkNote: "जगहों के दृश्य कलात्मक चित्रण हैं।",
  camera: "तस्वीर लें",
  cancel: "रद्द करें",
  cancelled: "रद्द कर दिया गया। आपकी तस्वीर यहीं है।",
  checking: "फ़ोटो बूथ खुला है या नहीं, जाँच रहे हैं…",
  choosePhoto: "तस्वीर चुनें",
  chooseScene: "अपनी जगह चुनें",
  closed: "फ़ोटो बूथ बंद है",
  closedDuring: "बूथ बंद हो गया है। तैयार तस्वीर अभी भी डाउनलोड या शेयर कर सकते हैं।",
  closedHelp: "नीचे दिए लिंक से Citius की यात्राएँ देख सकते हैं।",
  continue: "बिना सेव किए आगे बढ़ें",
  create: "मेरी तस्वीर बनाएँ",
  cutout: "पृष्ठभूमि बदलें",
  cutoutError: "पृष्ठभूमि नहीं हट सकी। फिर कोशिश करें, दूसरी तस्वीर चुनें या पूरी तस्वीर रखें।",
  downloaded: "डाउनलोड शुरू किया गया। डाउनलोड फ़ोल्डर जाँचें या तस्वीर गैलरी में सेव करें।",
  explore: "Citius Holidays की यात्राएँ देखें",
  explorePilgrimage: "तीर्थयात्राएँ देखें",
  firstLoad: "पृष्ठभूमि हटाने के लिए पहली बार लगभग 29 MB डाउनलोड होगा।",
  format: "तस्वीर का आकार",
  frame: "पूरी तस्वीर रखें",
  home: "Citius Holidays मुख्य पृष्ठ",
  horizontal: "बाएँ / दाएँ करें",
  language: "Language / भाषा",
  loading: "आपकी तस्वीर खुल रही है…",
  noScenes: "अभी कोई दृश्य उपलब्ध नहीं है। थोड़ी देर बाद फिर कोशिश करें।",
  photoHelp: "JPG, PNG या WebP, अधिकतम 12 MB। HEIC को पहले JPG में बदलें।",
  photoOptions: "तस्वीर या स्टाइल बदलें",
  photoStyle: "तस्वीर का स्टाइल",
  pilgrimage: "तीर्थयात्रा",
  plan: "यहाँ की यात्रा प्लान करें",
  portrait: "पोस्ट · 4:5",
  preparing: "कटआउट टूल तैयार हो रहा है…",
  preview: "अपनी तस्वीर देखें",
  previewAlt: "आपकी Citius तस्वीर का प्रीव्यू",
  previousResult: "पिछली तैयार तस्वीर",
  privacy: "तस्वीर इसी डिवाइस पर रहती है। जाने से पहले सेव करें।",
  privacyLink: "नीतियाँ और गोपनीयता",
  privileged: "स्टाफ़ प्रीव्यू: एडमिन या डायरेक्टर होने के कारण आप बूथ बंद होने पर भी तस्वीर बना सकते हैं।",
  processing: "लोगों को रखते हुए पृष्ठभूमि हटाई जा रही है…",
  renderError: "प्रीव्यू तैयार नहीं हो सका। आपकी तस्वीर यहीं है। इंटरनेट कनेक्शन जाँचकर फिर कोशिश करें।",
  rendering: "प्रीव्यू तैयार हो रहा है…",
  resetPlacement: "स्थिति रीसेट करें",
  retry: "फिर कोशिश करें",
  retryCutout: "कटआउट फिर बनाएँ",
  retryPreview: "प्रीव्यू फिर बनाएँ",
  save: "तस्वीर डाउनलोड करें",
  selected: "चयनित",
  share: "तस्वीर शेयर करें",
  shareCancelled: "शेयर करना रद्द किया गया। तस्वीर डाउनलोड या शेयर करने के लिए तैयार है।",
  shareFailed: "शेयर मेन्यू नहीं खुल सका। तस्वीर डाउनलोड करके गैलरी से शेयर करें।",
  shareHandedOff: "तस्वीर शेयर मेन्यू को दी गई है। चुने हुए ऐप में शेयर करना पूरा करें।",
  shareUnavailable:
    "इस ब्राउज़र से फ़ाइल शेयर नहीं हो सकती। तस्वीर डाउनलोड करें, फिर अपने पसंद के ऐप में पोस्ट करें।",
  sharing: "शेयर मेन्यू खुल रहा है…",
  size: "आकार",
  sourceAlt: "आपकी चुनी हुई तस्वीर, केवल इसी डिवाइस पर",
  startOver: "फिर शुरू करें",
  story: "स्टोरी · 9:16",
  title: "फ़ोटो बूथ",
  travel: "घूमने की जगहें",
  unavailable: "फ़ोटो बूथ की स्थिति जाँच नहीं सके। फिर कोशिश करें।",
  unsaved: "पहले तस्वीर सेव या शेयर कर लें। जाने या फिर शुरू करने पर यह तस्वीर हट जाएगी। बिना सेव किए आगे बढ़ें?",
  unsavedTitle: "अपनी तस्वीर सेव करें?",
  uploadError:
    "यह तस्वीर नहीं खुल सकी। 12 MB और 25 मेगापिक्सल से छोटी JPG, PNG या WebP तस्वीर चुनें। पिछली तस्वीर यहीं है।",
  vertical: "ऊपर / नीचे करें",
} satisfies Record<keyof typeof en, string>;

export type BoothCopyKey = keyof typeof en;
export function boothCopy(language: BoothLanguage) {
  return language === "hi" ? hi : en;
}
