import type { usePortalWorkspaceState } from "@/components/portal/usePortalWorkspaceState";

type PortalWorkspaceState = ReturnType<typeof usePortalWorkspaceState>;

/** Exact workspace fields used by the modal host before query arrays are normalized. */
export type PortalSpreadsheetModalWorkspaceSlice = Pick<
  PortalWorkspaceState,
  | "access"
  | "attachFinalizedPdf"
  | "attachProposalFile"
  | "attachQueryFile"
  | "closeModal"
  | "commitFlightImport"
  | "commitPassengerImport"
  | "error"
  | "flightItinerary"
  | "form"
  | "generateFinalizedPdfUploadUrl"
  | "generateProposalUploadUrl"
  | "generateQueryUploadUrl"
  | "getExpenseAttachmentUrl"
  | "getFinalizedPdfUrl"
  | "getPassengerExportDownload"
  | "getProposalAttachmentUrl"
  | "getQueryAttachmentUrl"
  | "has"
  | "isSaving"
  | "jobCards"
  | "leaveBalances"
  | "leaveHeadApproverCandidates"
  | "modal"
  | "passengerExportOperations"
  | "passengerImportOperations"
  | "patchForm"
  | "pendingExpenseProofFiles"
  | "pendingProposalFiles"
  | "pendingQueryFiles"
  | "pnrs"
  | "previewPassengerImport"
  | "startPassengerExport"
  | "proposals"
  | "queries"
  | "removeExpenseProof"
  | "removeFinalizedPdf"
  | "removeProposalAttachment"
  | "removeQueryAttachment"
  | "saveFlash"
  | "setPendingExpenseProofFiles"
  | "setPendingProposalFiles"
  | "setPendingQueryFiles"
  | "submit"
  | "team"
  | "travellers"
  | "travellersWithoutVisa"
  | "updateForm"
  | "visas"
>;
