import {
  buildPassportWorkbook,
  buildRoomingWorkbook,
  buildTravellerMasterWorkbook,
  buildVisaWorkbook,
  parsePassportWorkbookFile,
  parseRoomingWorkbookFile,
  parseTravellerMasterWorkbookFile,
  parseVisaWorkbookFile,
} from "./spreadsheetModalRuntime";

export const PASSENGER_IMPORT_MODAL_CONFIGS = [
  {
    fileLabel: "Ticketing passenger spreadsheet",
    modal: "passengerImport",
    successLabel: "Ticketing passenger import complete",
    title: "Import Ticketing Passenger List",
    uploadLabel: "Upload Ticketing List",
  },
  {
    emptyLabel: "No traveller master rows found.",
    fileLabel: "Traveller master spreadsheet",
    importKind: "traveller",
    modal: "travellerImport",
    parseWorkbookFile: parseTravellerMasterWorkbookFile,
    successLabel: "Traveller master import complete",
    title: "Import Traveller Master",
    uploadLabel: "Upload Traveller Master",
  },
  {
    emptyLabel: "No rooming rows found.",
    fileLabel: "Rooming spreadsheet",
    importKind: "rooming",
    modal: "roomingImport",
    parseWorkbookFile: parseRoomingWorkbookFile,
    successLabel: "Rooming import complete",
    title: "Import Rooming List",
    uploadLabel: "Upload Rooming",
  },
  {
    emptyLabel: "No passport rows found.",
    fileLabel: "Passport spreadsheet",
    modal: "passportImport",
    parseWorkbookFile: parsePassportWorkbookFile,
    successLabel: "Passport import complete",
    title: "Import Passport List",
    uploadLabel: "Upload Passports",
  },
  {
    emptyLabel: "No visa rows found.",
    fileLabel: "Visa spreadsheet",
    modal: "visaImport",
    parseWorkbookFile: parseVisaWorkbookFile,
    successLabel: "Visa import complete",
    title: "Import Visa List",
    uploadLabel: "Upload Visa Rows",
  },
] as const;

export const PASSENGER_EXPORT_MODAL_CONFIGS = [
  {
    exportKind: "passenger",
    filenameSuffix: "ticketing-passengers",
    modal: "passengerExport",
    subtitle: "Select a job card to download the ticketing passenger spreadsheet.",
    title: "Export Ticketing Passenger List",
  },
  {
    buildWorkbook: buildTravellerMasterWorkbook,
    exportKind: "traveller",
    filenameSuffix: "traveller-master",
    modal: "travellerExport",
    sheetName: "Master list",
    subtitle: "Select a job card to download the Master list sheet in the traveller master format.",
    title: "Export Traveller Master",
  },
  {
    buildWorkbook: buildRoomingWorkbook,
    exportKind: "rooming",
    filenameSuffix: "rooming",
    modal: "roomingExport",
    sheetName: "Rooming",
    subtitle: "Select a job card to download the Rooming sheet in the master-list format.",
    title: "Export Rooming List",
  },
  {
    buildWorkbook: buildPassportWorkbook,
    exportKind: "passport",
    filenameSuffix: "passport",
    modal: "passportExport",
    sheetName: "Passport",
    subtitle: "Select a job card to download the Passport sheet in the master-list format.",
    title: "Export Passport List",
  },
  {
    buildWorkbook: buildVisaWorkbook,
    exportKind: "visa",
    filenameSuffix: "visa",
    modal: "visaExport",
    sheetName: "Visa",
    subtitle: "Select a job card to download the Visa sheet in the master-list format.",
    title: "Export Visa List",
  },
] as const;
